apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nitesh2611/user-svc:17
          ports:
            - containerPort: 8081
          env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/userdb?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: 1   
