FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=userdb
ENV MYSQL_USER=root 
ENV MYSQL_PASSWORD=root 

COPY init.sql /docker-entrypoint-initdb.d/
EXPOSE 3306


ENTRYPOINT ["/entrypoint.sh", "mysqld"]